name: bloc_firebase_login
description: Bloc Firebase Login
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  authentication_repository:
    path: packages/authentication_repository
  bloc: ^9.0.0
  bloc_concurrency: ^0.3.0
  custom_widgets:
    path: packages/custom_widgets
  equatable: ^2.0.7
  firebase_auth_platform_interface: ^7.5.0
  firebase_core: ^3.10.0
  flow_builder: ^0.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.8.0
  form_inputs:
    path: packages/form_inputs
  formz: ^0.8.0
  intl: ^0.19.0
  rxdart: ^0.28.0
  stream_transform: ^2.1.1

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  assets:
    - assets/images/
  uses-material-design: true
  generate: true
