name: bloc_firebase_login
description: Bloc Firebase Login
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.6.0

dependencies:
  authentication_repository:
    path: packages/authentication_repository
  bloc: ^8.1.4
  equatable: ^2.0.7
  firebase_core: ^3.10.0
  flow_builder: ^0.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
