name: authentication_repository
description: A dart package which manages the authentication domain.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  cache:
    path: ../cache
  equatable: ^2.0.7
  firebase_auth: ^5.4.0
  firebase_core: ^3.10.0
  flutter:
    sdk: flutter
  google_sign_in: ^6.2.2
  meta: ^1.15.0

dev_dependencies:
  firebase_auth_platform_interface: ^7.5.0
  firebase_core_platform_interface: ^5.4.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  plugin_platform_interface: ^2.1.8
  test: ^1.25.8
  very_good_analysis: ^6.0.0
