// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKNQ3Z8uLMVOf8bp0fgeVkK4k46CnoEPg',
    appId: '1:95357842105:web:0140d602e04da491826168',
    messagingSenderId: '95357842105',
    projectId: 'bloc-firebase-login-ae3c3',
    authDomain: 'bloc-firebase-login-ae3c3.firebaseapp.com',
    storageBucket: 'bloc-firebase-login-ae3c3.firebasestorage.app',
    measurementId: 'G-EBTWCRXY4S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-wxM02HMUCqNVkzMR3q3n6fEpdnHbbs0',
    appId: '1:95357842105:android:bb57e01a6db688d6826168',
    messagingSenderId: '95357842105',
    projectId: 'bloc-firebase-login-ae3c3',
    storageBucket: 'bloc-firebase-login-ae3c3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCv4G9MjsUSksvqQOjjF7XQkdCAnUnEInY',
    appId: '1:95357842105:ios:e9063908522ecf23826168',
    messagingSenderId: '95357842105',
    projectId: 'bloc-firebase-login-ae3c3',
    storageBucket: 'bloc-firebase-login-ae3c3.firebasestorage.app',
    iosBundleId: 'com.csarevalo.BlocFirebaseLogin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKNQ3Z8uLMVOf8bp0fgeVkK4k46CnoEPg',
    appId: '1:95357842105:web:533bc7810427f3ee826168',
    messagingSenderId: '95357842105',
    projectId: 'bloc-firebase-login-ae3c3',
    authDomain: 'bloc-firebase-login-ae3c3.firebaseapp.com',
    storageBucket: 'bloc-firebase-login-ae3c3.firebasestorage.app',
    measurementId: 'G-BT85TMMGYF',
  );
}
